/**
 * This file was generated by the Jeddict
 */
package awt.server.model;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * @author Utente
 */
@Entity
public class AnnotationTaskInstance {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String skyline;

    @OneToOne(targetEntity = Image.class)
    private Image image;

    @ManyToOne(targetEntity = AnnotationTask.class)
    private AnnotationTask annotationTask;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSkyline() {
        return this.skyline;
    }

    public void setSkyline(String skyline) {
        this.skyline = skyline;
    }

    public Image getImage() {
        return image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    public AnnotationTask getAnnotationTask() {
        return annotationTask;
    }

    public void setAnnotationTask(AnnotationTask annotationTask) {
        this.annotationTask = annotationTask;
    }


}