/**
 * This file was generated by the Jeddict
 */
package awt.server.model;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

/**
 * @author Utente
 */
@Entity
public class AnnotationTask extends Task {

    @OneToMany(targetEntity = AnnotationTaskInstance.class, mappedBy = "annotationTask")
    private List<AnnotationTaskInstance> annotationTaskInstance;

    public List<AnnotationTaskInstance> getAnnotationTaskInstances() {
        return this.annotationTaskInstance;
    }

    public void setAnnotationTaskInstances(List<AnnotationTaskInstance> ANNOTATION_TASK_INSTANCEs) {
        this.annotationTaskInstance = ANNOTATION_TASK_INSTANCEs;
    }

}