/**
 * This file was generated by the Jeddict
 */
package awt.server.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * @author Utente
 */
@Entity
public class AnnotationTaskInstance {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Lob
    private String skyline; //o a valore o notAlready
     public static final String NOTALREADY = "notAlready";

    @OneToOne(targetEntity = Image.class)
    private Image image;

    @ManyToOne(targetEntity = Task.class)
    private Task annotationTask;

    public AnnotationTaskInstance(String skyline, Image image, Task annotationTask) {
        this.skyline = skyline;
        this.image = image;
        this.annotationTask = annotationTask;
    }

    public AnnotationTaskInstance() {
    }
   

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSkyline() {
        return this.skyline;
    }

    public void setSkyline(String skyline) {
        this.skyline = skyline;
    }

    public Image getImage() {
        return image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    public Task getAnnotationTask() {
        return annotationTask;
    }

    public void setAnnotationTask(Task annotationTask) {
        this.annotationTask = annotationTask;
    }


}