/**
 * This file was generated by the Jeddict
 */
package awt.server.model;

import awt.server.model.convenience.CampaignStatistics;
import awt.server.dto.NewCampaignDTO;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * @author Utente
 */
@Entity
/*@NamedQuery(
        name = "getMasterCampagins",
        query = "select c from Campaign c where c.master.id = ?1"
)*/
public class Campaign {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    @NotNull
    private String name;

    @Basic
    private String status;
    public static final String STARTED = "started", TERMINATED = "ended", ready = "ready";

    @Basic
    @NotNull
    @Min(value = 1, message = "Minimum 1")
    private int selectionReplica;

    @Basic
    @NotNull
    @Min(value = 1, message = "Minimum 1")
    private int threshold;

    @Basic
    @NotNull
    @Min(value = 1)
    private int annotationReplica;

    @Basic
    @NotNull
    @Min(value = 1, message = "Min 1")
    @Max(value = 10, message = "Max 10")
    private int annotationSize;

    @OneToOne(targetEntity = CampaignStatistics.class, mappedBy = "campaign")
    private CampaignStatistics campaignStatistics;

    @ManyToOne(targetEntity = Master.class)
    private Master master;

    @OneToMany(targetEntity = Image.class, mappedBy = "campaign")
    private List<Image> images;

    public Campaign(Long id, String name, String status, int selectionReplica, int threshold, int annotationReplica, int annotation_size, CampaignStatistics campaignStatistics, Master master, List<Image> images) {
        this.id = id;
        this.name = name;
        this.status = status;
        this.selectionReplica = selectionReplica;
        this.threshold = threshold;
        this.annotationReplica = annotationReplica;
        this.annotationSize = annotation_size;
        this.campaignStatistics = campaignStatistics;
        this.master = master;
        this.images = images;
    }

    public Campaign() {
    }
    
     public Campaign(NewCampaignDTO c, String status, Master m) {
        this.name = c.getName();
        this.status = status;
        this.selectionReplica = c.getSelection_replica();
        this.threshold = c.getThreshold();
        this.annotationReplica = c.getAnnotation_replica();
        this.annotationSize = c.getAnnotation_size();
        this.master = m;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

  
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

 
    public int getThreshold() {
        return this.threshold;
    }

    public void setThreshold(int threshold) {
        this.threshold = threshold;
    }

    public int getSelectionReplica() {
        return selectionReplica;
    }

    public void setSelectionReplica(int selectionReplica) {
        this.selectionReplica = selectionReplica;
    }

    public int getAnnotationReplica() {
        return annotationReplica;
    }

    public void setAnnotationReplica(int annotationReplica) {
        this.annotationReplica = annotationReplica;
    }

    public int getAnnotationSize() {
        return this.annotationSize;
    }

    public void setAnnotationSize(int annotationSize) {
        this.annotationSize = annotationSize;
    }

    public CampaignStatistics getCampaignStatistics() {
        return campaignStatistics;
    }

    public void setCampaignStatistics(CampaignStatistics campaignStatistics) {
        this.campaignStatistics = campaignStatistics;
    }

    public Master getMaster() {
        return master;
    }

    public void setMaster(Master master) {
        this.master = master;
    }

    public List<Image> getImages() {
        return images;
    }

    public void setImages(List<Image> images) {
        this.images = images;
    }

   

}