/**
 * This file was generated by the Jeddict
 */
package awt.server.model;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * @author Utente
 */
@Entity
public class Campaign {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    @NotNull
    private String name;

    @Basic
    private String status;

    @Basic
    @NotNull
    @Min(value = 1, message = "Minimum 1")
    private int selectionReplica;

    @Basic
    @NotNull
    @Min(value = 1, message = "Minimum 1")
    private int threshold;

    @Basic
    @NotNull
    @Min(value = 1)
    private int annotationReplica;

    @Basic
    @NotNull
    @Min(value = 1, message = "Min 1")
    @Max(value = 10, message = "Max 10")
    private int annotation_size;

    @OneToOne(targetEntity = CampaignStatistics.class, mappedBy = "campaign")
    private CampaignStatistics campaignStatistics;

    @ManyToOne(targetEntity = Master.class)
    private Master master;

    @OneToMany(targetEntity = Image.class, mappedBy = "campaign")
    private List<Image> images;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

  
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

 
    public int getThreshold() {
        return this.threshold;
    }

    public void setThreshold(int threshold) {
        this.threshold = threshold;
    }

    public int getSelectionReplica() {
        return selectionReplica;
    }

    public void setSelectionReplica(int selectionReplica) {
        this.selectionReplica = selectionReplica;
    }

    public int getAnnotationReplica() {
        return annotationReplica;
    }

    public void setAnnotationReplica(int annotationReplica) {
        this.annotationReplica = annotationReplica;
    }

    public int getAnnotation_size() {
        return this.annotation_size;
    }

    public void setAnnotation_size(int annotation_size) {
        this.annotation_size = annotation_size;
    }

    public CampaignStatistics getCampaignStatistics() {
        return campaignStatistics;
    }

    public void setCampaignStatistics(CampaignStatistics campaignStatistics) {
        this.campaignStatistics = campaignStatistics;
    }

    public Master getMaster() {
        return master;
    }

    public void setMaster(Master master) {
        this.master = master;
    }

    public List<Image> getImages() {
        return images;
    }

    public void setImages(List<Image> images) {
        this.images = images;
    }

   

}