/**
 * This file was generated by the Jeddict
 */
package awt.server.model;

import awt.server.dto.RegistrationDetailsDTO;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

/**
 * @author Utente
 */
@Entity
public class Master extends User {

    @OneToMany(targetEntity = Campaign.class, mappedBy = "master")
    private List<Campaign> campaigns;
    
    public Master(RegistrationDetailsDTO dto){
        super(dto);
        campaigns = null;
    }

    public List<Campaign> getCampaigns() {
        return campaigns;
    }

    public void setCampaigns(List<Campaign> campaigns) {
        this.campaigns = campaigns;
    }


}