/**
 * This file was generated by the Jeddict
 */
package awt.server.model;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;

/**
 * @author Utente
 */
@Entity

public class SelectionTaskInstance {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String selected; //accepted, rejected, notAlready
    public static final String ACCEPTED = "accepted", REJECTED = "rejected", NOTALREADY = "notAlready";

    @OneToOne(targetEntity = Image.class)
    private Image image;

    @ManyToOne(targetEntity = Task.class)
    private Task selectionTask;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSelected() {
        return this.selected;
    }

    public void setSelected(String selected) {
        this.selected = selected;
    }

    public Image getImage() {
        return image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    public Task getSelectionTask() {
        return selectionTask;
    }

    public void setSelectionTask(Task selectionTask) {
        this.selectionTask = selectionTask;
    }

   

}