/**
 * This file was generated by the Jeddict
 */
package awt.server.model;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

/**
 * @author Utente
 */
@Entity
public class SelectionTask extends Task {

    @OneToMany(targetEntity = SelectionTaskInstance.class, mappedBy = "selectionTask")
    private List<SelectionTaskInstance> selectionTaskInstances;

    public List<SelectionTaskInstance> getSelectionTaskInstances() {
        return selectionTaskInstances;
    }

    public void setSelectionTaskInstances(List<SelectionTaskInstance> selectionTaskInstances) {
        this.selectionTaskInstances = selectionTaskInstances;
    }

  

}