/**
 * This file was generated by the Jeddict
 */
package awt.server.model;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;

/**
 * @author Utente
 */
@Entity
 /*@NamedQuery(
            name = "getWorkerSelectionTaskForCampaign",
            query = "Select t from SelectionTask t where t.worker = ?1  and t.campaign.id = ?2"
    )*/
public class SelectionTask extends Task {

    public SelectionTask(Long id, String statusCompleted, Worker worker, Campaign campaign) {
        super(id, statusCompleted, worker, campaign);
    }

    public SelectionTask() {
    }

    @OneToMany(targetEntity = SelectionTaskInstance.class, mappedBy = "selectionTask")
    private List<SelectionTaskInstance> selectionTaskInstances;

    public List<SelectionTaskInstance> getSelectionTaskInstances() {
        return selectionTaskInstances;
    }

    public void setSelectionTaskInstances(List<SelectionTaskInstance> selectionTaskInstances) {
        this.selectionTaskInstances = selectionTaskInstances;
    }

  

}